// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsTL0FlMJQWez_sb-x2zO_77wc7LWpw9Y',
    appId: '1:152199450594:web:10043ae9581a0dd6e933bb',
    messagingSenderId: '152199450594',
    projectId: 'todo-22364',
    authDomain: 'todo-22364.firebaseapp.com',
    storageBucket: 'todo-22364.firebasestorage.app',
    measurementId: 'G-02MK1GJF9X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaYaaog-V48G638I1IWpqKpN86gOYQYoQ',
    appId: '1:152199450594:android:509c0747abbe3abee933bb',
    messagingSenderId: '152199450594',
    projectId: 'todo-22364',
    storageBucket: 'todo-22364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NQcEVsKhlWQE8J9P07UvW4IJ0eYvePo',
    appId: '1:152199450594:ios:88dd65afc5ffc851e933bb',
    messagingSenderId: '152199450594',
    projectId: 'todo-22364',
    storageBucket: 'todo-22364.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6NQcEVsKhlWQE8J9P07UvW4IJ0eYvePo',
    appId: '1:152199450594:ios:88dd65afc5ffc851e933bb',
    messagingSenderId: '152199450594',
    projectId: 'todo-22364',
    storageBucket: 'todo-22364.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsTL0FlMJQWez_sb-x2zO_77wc7LWpw9Y',
    appId: '1:152199450594:web:aaa49ff1b54f46eae933bb',
    messagingSenderId: '152199450594',
    projectId: 'todo-22364',
    authDomain: 'todo-22364.firebaseapp.com',
    storageBucket: 'todo-22364.firebasestorage.app',
    measurementId: 'G-1HP1GF9QVJ',
  );
}
